Add SampleSheet info for cellularity and diagnoses for GMS Solid Tumor.
Clinical-Genomics-Lund/clarity_scripts pull request #28
Opened 2023-03-29 11:20 UTC by ErikBergman

Until now, diagnoses for GMS Solid Tumor has been missing, only being left as "other". This update adds them, currently only using the code words from Bioinformatics.

Additionally, the Cellularity (%) field is added at the end of the description string.

2023-03-30 06:18 UTC, Bella2347 commented on illumina/GetSampleInfoForSampleSheet.py
> +            DiagnosisDict = { "Hematologisk neoplasi" : "Hem" ,
This Dict was outside the if-statement on row 24, will there be any consequences now that it has been moved inside the if-statement? What analysis will now not have a DiagnosisDict that needes it?

2023-03-30 06:20 UTC, Bella2347 commented on illumina/GetSampleInfoForSampleSheet.py
> +                 Cellularity)
This if-statement (row 277) also include GMSLymphoma, and that analysis will also be affected by these changes, has that been asked for?

2023-03-30 06:25 UTC, Bella2347 commented on illumina/GetSampleInfoForSampleSheet.py
Comment about row 76. It looks like if a user has left the UDF/Diagnosis field empty it will be other in the description field, is that the case or am I missing something?
This should not be possible for GMSSolidTumor. If no value is give, an error should be thrown, the script fail and the user should be told which sample is missing a value for Diagnosis.

2023-03-30 06:26 UTC, Bella2347 requested changes
See comments

2023-03-30 06:28 UTC, ErikBergman commented on illumina/GetSampleInfoForSampleSheet.py
> +                 Cellularity)
Right now, the Cellularity field will be an empty string in all cases except GMS Solid Tumor at this point, in case the field should become relevant in the future. But I could remove it for now.

2023-03-30 06:37 UTC, ErikBergman commented on illumina/GetSampleInfoForSampleSheet.py
Good point, will fix.

2023-03-30 13:18 UTC, Bella2347 commented on illumina/GetSampleInfoForSampleSheet.py
> +                 Cellularity)
It will only affect GMSLymphoma which is not an active panel (still in testing I think). It sounded like Viktor did not care or think it would be a problem but ask him, he decides

2023-03-31 08:22 UTC, Bella2347 approved these changes

2023-03-31 08:22 UTC, merged