Kapa hamilton
Clinical-Genomics-Lund/clarity_scripts pull request #34
Opened 2023-04-17 14:06 UTC by Bella2347

New pipetting robots needs new protocols in Clarity.
KAPA consists of two different protocols, HyperPrep and HyperPlus.
The KAPA method is divided into 6 processes on the Hamilton Method.

1. Enzymatic fragmentation (only HyperPlus)
2. End repair
3. Ligation
4. Ligation clean up
5. Amplification
6. Purification

Users will run process 1-5 in the Pre-PCR lab, and process 6 in the Post-PCR lab.
All processes can be run in a single day or over two days. Depending on how many processes are run at the same time, different reagents will be needed.

[customPackageSMD/py3functions.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/34/files#diff-c32251a4a1bd72fbcab58661781997707b4285f8ee59b40a444c5aa9a0df325c)
- A class for Well has been made. Clarity gives wells in the format A:1 but input/result files from instruments might have a different format. 
- The input argument button has been added, says if the automation is triggered by a button in Clarity or not

[common/COMMON_checkLableReagent_IDT10.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/34/files#diff-f4fb493f22435c810e449fcf9f5a454b58e0bedfb58bca6da63a701b5831b1ca)
Checks that the choosen reagent lots match the choosen index for samples in an index step. Used only for IDT10 indexes.
- Checks that a reagent lot is choosen for each plate used (assumes "platta/plate" in reagent lot name)
- Checks that no additional reagent lots are choosen
- Checks that someone has counter read the step

[hamilton/HAMILTON_copyLabelGroup.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/34/files#diff-6e0bcacc598ac5d92c17285e09f558f4013ef980a34516c534e6cb6af5befe99)
Copies the choosen label group on none index steps.

[hamilton/HAMILTON_inputfile.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/34/files#diff-63313393d18a8be2b7ca75a781f692a689575ea514a0136d4a883275c9cd5da9)
Creates an input file for the Hamilton instruments.

Header of input files:
> Sample_ID,Sample_Position,Index1_ID,Index_PlateNum,Index1_Pos

[hamilton/HAMILTON_mixFile.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/34/files#diff-06e47cc7384cd151b9aeed7f6dc370bb3855a33ed1803cee138ece8069197179)
1. First this script checks which wells will be used on each of the two possible index plates.
   - Samples are sorted column wise after their placement
   - If a sample has a lower index well than the sample before, it is assumed that the index plate has changed. 
The wells used in each index plate is displayed on the step.

2. In the next part the reagents needed are calculated.
The Hamilton processes the step covers are given as a StepUDF, the method is also given. From this the reagents from those processes are taken from the variable volumes in [hamilton/HAMILTON_mixVolumes.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/34/files#diff-54bfb8f6536dec96561f84c3a864e2e8b207a4a77feb462150c981f1e73a1792)
If the reagent is in tubes, it is calculated if more than one tube is needed. The volumes needed and if a fixed number of tubes should be used is copied from the methods on the Hamilton instruments.

3. In the last part of the script an excelfile is made displaying all the reagent volumes.

[hamilton/HAMILTON_mixVolumes_TEST.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/34/files#diff-e36b625fb020302a41fe3e3e86f3af757b9a98cca1065c2ef3a3c263ea052253)
This script calculates the volumes and number of tubes for all processes for a number of samples from 1-96. This is used to compare to the Hamilton method.

2023-09-21 14:17 UTC, Bella2347 commented
The script for creating mixfile and inputfile will also be used for IDPT. For the step 'IDPT - Library Prep with Hamilton v.1' the following changes in automation triggers must be made and change indexes from three groups to one 'MICRO IDT10_UDI_Adapter1-384'. These changes have been tested in ReQtest test run; https://secure.reqtest.com/app/tests/test-run/view/view-test-run-details/723732.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/227411/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/227411/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:" ";}
@page
	{margin:.75in .7in .75in .7in;
	mso-header-margin:.3in;
	mso-footer-margin:.3in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
-->
</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | Old triggers | Old triggers | New triggers | New triggers
-- | -- | -- | -- | --
Automation Name | Trigger Location | Trigger Style | Trigger Location | Trigger Style
(WP) COMMON - Check 96-well plate Name (.py) |   |   | Placement | Automatic upon exit
(WP) COMMON - Check Label Group IDT10 (.py) |   |   | Record Details | Automatic upon exit
(WP) Hamilton - 1. Mix file (.py) | Not Used |   | Not Used |  
(WP) Hamilton - 2. Check Labels, Create Input   File (.py) | Not Used |   | Not Used |  
(WP) Hamilton - 2. Check Signature, Create   Input File (.py) | Not Used |   | Not Used |  
(WP) Hamilton - Create Mix File and Input File   (.py) |   |   | Record Details | Manual button
COMMON - Check Container Name (.jar) | Placement | Automatic upon exit | Not Used |  
COMMON - Check index duplicates (.py) | Add Labels | Automatic upon exit | Add Labels | Automatic upon exit
COMMON - Check Reagent Kit to Label Group   (.py) | Record Details | Automatic upon exit | Not Used |  
COMMON - Copy Label Group (.py) | Step | Automatic upon entry | Step | Automatic upon entry
IDPT - Hamilton Input File (.py) | Record Details | Manual button | Not Used |  
IDPT - Hamilton Mix file (.py) | Record Details | Automatic upon entry | Not Used |  



</body>

</html>

2023-10-02 06:12 UTC, ErikBergman commented on common/COMMON_checkContainerName.py
> +        if name.startswith("27-"):
I'd define "27-" as a variable

2023-10-02 06:15 UTC, ErikBergman commented on common/COMMON_checkLableReagent_IDT10.py
> +                logging.error("Index has wrong format") # index=label
Should it allow the script to continue during formatting errors?

2023-10-02 06:16 UTC, ErikBergman commented on common/COMMON_checkLableReagent_IDT10.py
> +            label = re.search("(Adapter|IDT10_)(\d+)", art.reagent_labels[0])
Describe the regex pattern in words

2023-10-02 06:27 UTC, ErikBergman commented on common/COMMON_checkContainerName.py
> +sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "customPackageSMD"))
I can't quite wrap my head around importing python modules from non-descendant directives. I generally use a variant of your method like this case but I would have thought that it could be done cleaner. Oh well.

2023-10-02 06:33 UTC, ErikBergman commented on customPackageSMD/py3functions.py
> +        row = re.search("([A-Z])", well.upper())[1]
Is it possible that this doesn't find a match? If so, add some error handling.

2023-10-02 06:35 UTC, ErikBergman commented on customPackageSMD/py3functions.py
> +    def _to_alpha(self, well, traversal):
I'd begin with a comment here, it looks a bit complex.

2023-10-02 06:35 UTC, ErikBergman commented on customPackageSMD/py3functions.py
> +    def _from_alpha(self):
And here too

2023-10-02 08:18 UTC, ErikBergman requested changes

2023-10-02 08:18 UTC, ErikBergman commented on hamilton/HAMILTON_utils.py
> +        reagent_match = re.search("(Platta|Plate)(\d) (\d{1,2}[ABCDEFGH])", art.reagent_labels[0])
Comment regex

2023-10-05 11:43 UTC, Bella2347 commented on common/COMMON_checkLableReagent_IDT10.py
> +                logging.error("Index has wrong format") # index=label
In this case yes. 
When `py3functions.logger_end_script(lims, args["processID"], args["BUTTON"])` is run at the end of the script the status of the script will be set to Error if any errors has been logged and when the status is set to error the user is not allowed to continue if the script is triggered on start/exit of a step. 
We want to continue to check all samples instead of stopping the script at the first error incase more than one sample needs to be looked at.

2023-10-05 11:52 UTC, Bella2347 commented on common/COMMON_checkContainerName.py
> +sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "customPackageSMD"))
I have not tried to find a neater solution but if you find something we can just change it. 
Importing scripts in the same folder is easy, if they are in other folders the folders path needs to be adde to PATH. A relative path is created so that, for example, the customPackageSMD in the same git repo is used.

2023-10-05 12:54 UTC, Bella2347 commented on hamilton/HAMILTON_mixVolumes.py
> +                f"Container type is not valid. Valid container types: "+
I don't want a new line in the string, I want to divide the string on two lines so that the line is not too long in the script. I don't understand how adding a \n would work?

2023-10-06 06:45 UTC, Bella2347 commented on customPackageSMD/py3functions.py
> +    def list(self):
I thought it would still work since it is only used in this class?

2023-10-06 06:50 UTC, ErikBergman commented on customPackageSMD/py3functions.py
> +    def list(self):
Surely it will work, it's rather a matter of future-proofing. The PEP 8 style guide brings this up: https://peps.python.org/pep-0008/#function-and-method-arguments

2023-10-09 11:20 UTC, ErikBergman approved these changes

2023-10-16 06:18 UTC, merged