Pharmacogenetics
Clinical-Genomics-Lund/clarity_scripts pull request #57
Opened 2024-01-02 14:02 UTC by Bella2347

In the Sequencing QC step for KAPA Twist send Solid Tumor samples to the Pharmacogenetics step.

Ovarialcancer normal samples are already routed to an extra step. Wrote a new scrip to work for both ovarialcancer and pharmacogenetics. 

In the pharmacogenetics step a html report is retrived for each sample. The QC in the report is checked and patient information is added. A PDF report is created from the html report and attached to each sample in Clarity. When the step is completed the reports are moved to the RS LIMS folder.

2024-01-02 14:10 UTC, Bella2347 commented
```
WARNING: Ignored `image-rendering: smooth` at 18:7, invalid value.
WARNING: Ignored `white-space: -moz-pre-wrap` at 184:7, invalid value.
WARNING: Ignored `white-space: -pre-wrap` at 185:7, invalid value.
WARNING: Ignored `white-space: -o-pre-wrap` at 186:7, invalid value.
WARNING: Error: Expected <ident> for declaration name, got hash. at 202:7.
WARNING: Error: Expected <ident> for declaration name, got hash. at 216:7.
```
I get these warning when I create the report (ran from command line)
@ramsainanduri can you fix it?

2024-01-03 09:50 UTC, Bella2347 commented
[kapaTwist/OvarialNormalPaired_routeToDataAnalysis.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/57/files#diff-9e629ba6cc8311481d3da307dab191d561767d066309c3b3ccb58d71ec4e9341) has been replaced by [kapaTwist/KAPA_routeSamplesDataAnalysis.py](https://github.com/Clinical-Genomics-Lund/clarity_scripts/pull/57/files#diff-fd85b58d8e52f2308b71a84a3df7ac1c76b4760ce4886bcde47ea5234ede8ae0)
ReQtest test for this: [(KAPA) Sequencing QC - Routing](https://secure.reqtest.com/app/tests/test-case/view/view-detail/4048972/details) and [(KAPA) Sequencing QC](https://secure.reqtest.com/app/tests/test-case/view/view-detail/3815391/details)

2024-01-03 09:51 UTC, Bella2347 commented
ReQtest test case for pharmacogenetics step [(Pharmacogenetics) Data Analysis](https://secure.reqtest.com/app/tests/test-case/view/view-detail/4048981/details)

2024-01-04 19:44 UTC, ramsainanduri commented
> ```
> WARNING: Ignored `image-rendering: smooth` at 18:7, invalid value.
> WARNING: Ignored `white-space: -moz-pre-wrap` at 184:7, invalid value.
> WARNING: Ignored `white-space: -pre-wrap` at 185:7, invalid value.
> WARNING: Ignored `white-space: -o-pre-wrap` at 186:7, invalid value.
> WARNING: Error: Expected <ident> for declaration name, got hash. at 202:7.
> WARNING: Error: Expected <ident> for declaration name, got hash. at 216:7.
> ```
> 
> I get these warning when I create the report (ran from command line) @ramsainanduri can you fix it?

I have fixed this upstream from the pipeline

2024-01-04 19:46 UTC, ramsainanduri commented on pharmacogenetics/pharmacogenetics_createReport.py
Looks good

2024-01-05 09:56 UTC, ramsainanduri approved these changes
LGTM. I have not tested the scripts responsible for moving file to RS LIMS

2024-01-09 15:21 UTC, Bella2347 commented
Updated with to commits so that it looks for a report named as the solid tumor sample. 

I updated the test-case with two new samples:
- ST-NORMAL # report should be named ST-TUMOR
- ST-MISSING-PAIR # paired name is missing, should give error

2024-02-20 14:26 UTC, ramsainanduri commented
Updated report path on Lennart

2024-02-21 10:31 UTC, alkc requested changes
Some comments. Looks good otherwise!

2024-02-21 10:31 UTC, alkc commented on common/COMMON_moveReportToRSlims.py
> +RS_LIMS_PAHT = "/mnt/limsrs-clarity/PDF/in/"
```suggestion
RS_LIMS_PATH = "/mnt/limsrs-clarity/PDF/in/"
```

typo. remember to change elsewhere.

2024-02-21 10:31 UTC, alkc commented on common/COMMON_moveReportToRSlims.py
> +        if not "complete" in action["action"]:
What's in `action["action"]` ?

Is it a list or string?

2024-02-21 10:31 UTC, alkc commented on common/COMMON_moveReportToRSlims.py
> +                    logging.info(f"Test sample, report not moved, {outart.name}")
```suggestion
            if not outart.files:
                logging.info(f"No report for {outart.name}")
                continue

            # Get the name of the file in Clarity LIMS
            filename = outart.files[0].original_location.split("/")[-1]
            # Create the path to the RS LIMS folder
            path = RS_LIMS_PAHT + filename
            # Get the file as a readcontent object
            read_content = lims.get_file_contents(uri=outart.files[0].uri)

            project = outart.samples[0].project
            if project.udf.get("Project Classification", "") == "Laborativ - Klinisk":
                # Write binary report
                with open(path, "wb") as f:
                    f.write(read_content.read())
                logging.info(f"Report moved to RS Lims, {filename}")
            else:
                logging.info(f"Test sample, report not moved, {outart.name}")
```

You can just add a `continue` after L43  to advance the for loop and drop the first else-block.

2024-02-21 10:31 UTC, alkc commented on pharmacogenetics/pharmacogenetics_createReport.py
> +    remove_tmp(dir_path, tmp_html_path, tmp_pdf_path)
Look into tempfile stdlib module for python: 

https://docs.python.org/3/library/tempfile.html

It takes care of automatic creation and removal of tmp files for you.

If the removal of the tmp file is important (for example to avoid unnecessary storage of personal data) and if you don't want to switch to the tempfile module right now, then consider wrapping the code between L123-L131 in a try-except-finally block, where the `remove_tmp(dir_path, tmp_html_path, tmp_pdf_path)` is added in the `finally:` block to ensure the tmp file is removed even if the code in `try:` block fails.

2024-02-21 10:31 UTC, alkc commented on common/COMMON_moveReportToRSlims.py
> +from genologics.entities import Process
👍

2024-02-21 10:31 UTC, alkc commented on common/COMMON_moveReportToRSlims.py
> +def get_outart(outarts, inart):
Consider adding type hints to yr functions

2024-02-21 10:31 UTC, alkc commented on common/COMMON_moveReportToRSlims.py
> +                path = RS_LIMS_PAHT + filename
```suggestion
                path = RS_LIMS_PATH + filename
```

2024-02-21 10:31 UTC, alkc commented on pharmacogenetics/pharmacogenetics_createReport.py
> +from genologics.entities import *
Try to avoid star imports.

2024-02-21 10:31 UTC, alkc commented on pharmacogenetics/pharmacogenetics_createReport.py
> +def retrive_html_report(sample):
```suggestion
def retrieve_html_report(sample):
```

typo

2024-02-21 10:31 UTC, alkc commented on pharmacogenetics/pharmacogenetics_createReport.py
> +    """Check QC values in file and complie result for failed QC values.
```suggestion
    """Check QC values in file and compile result for failed QC values.
```

2024-02-21 12:31 UTC, Bella2347 commented on common/COMMON_moveReportToRSlims.py
> +        if not "complete" in action["action"]:
That are things I also wonder and have to figure out. 
`process.step.actions.next_actions` returns a list of dicts. Each dict looks like this 
`{"artifact" : Artifact, "action" : str}`
Action can only be some predefined values (complete, remove, repeat, nextstep, completerepeat and more I don't know).
I added a comment about this.

2024-02-21 13:12 UTC, Bella2347 commented on pharmacogenetics/pharmacogenetics_createReport.py
> +    remove_tmp(dir_path, tmp_html_path, tmp_pdf_path)
I did not know about that one!

2024-02-21 14:04 UTC, alkc approved these changes
Looks good!

2024-02-21 14:04 UTC, alkc commented on pharmacogenetics/pharmacogenetics_createReport.py
> +    with TemporaryDirectory() as tmpdir:
Nice! 👍

2024-02-21 14:04 UTC, alkc commented on common/COMMON_moveReportToRSlims.py
> +        filename = outart.files[0].original_location.split("/")[-1]
```suggestion
        filename = os.path.basename(outart.files[0].original_location)
```

since`os` is already imported in this module

2024-02-22 09:15 UTC, Bella2347 commented
Test run on [ReQtest](https://secure.reqtest.com/app/tests/test-run/view/view-test-run-details/752227)

2024-02-22 09:18 UTC, merged