Solid Tumor RNA and qPCR for FFPE DNA
Clinical-Genomics-Lund/clarity_scripts pull request #58
Opened 2024-01-16 11:09 UTC by Bella2347

This PR includes both the changes to add the SolidTumorRNA panel to Clarity and a qPCR step for FFPE DNA.

2024-01-18 09:29 UTC, Bella2347 commented
All steps have been tested and documented in [ReQtest](https://secure.reqtest.com/app/tests/test-run/view/view-test-run-details/753795). 
- KAPA RNA protocol
- TWIST for KAPA RNA and all other KAPA regression test samples
- Library qPCR step for:
  - LymphoTrack
  - WGS
  - Oncomine Focus + CF
- Initial qPCR step for DNA FFPE

For the qPCR step the calculated pM concentration has been compared and is the same.

2024-01-19 05:11 UTC, ErikBergman requested changes

2024-01-19 07:38 UTC, Bella2347 commented on customPackageSMD/ServerMap.py
> +        self.__dict__ = self
No it is so I can create an object that can have different values for claritylims and claritytest be always have the same keys.

ex. 8-strip is a container on both test and production server. On test it has the ID=54 and on prod=4. The name of the container can be changes, the ID can never be changed. I want to use the ID so that is does not break if someone where to change the name of the container. I cannot hardcode the ID since it is different on test and prod.
```
8strip_container = ServerMap(4, 54)
import socket
server = socket.gethostname().split(".")[0] # gets the servername
8strip_container[server] # this gives me the ID for the server I am on
```

But I guess I could do it like this:
```
import socket
server = socket.gethostname().split(".")[0]
class ServerMap():
    def __init__(self, claritylims, claritytest):
        if server == "clarity-test":
            self.id = claritytest
        else:
            self.id = claritylims
```

2024-01-19 07:39 UTC, Bella2347 commented on customPackageSMD/ServerMap.py
> +    def contains(self, item_id):
An exception for what? It returns False if the item_id is not in the collection

2024-01-19 09:18 UTC, Bella2347 commented on qPCR/qPCR_dilution.py
> +    workbook = xlsxwriter.Workbook(args["fileNAME"] + ".xlsx")
This will only happen if one runs it from the command line and then I feel that it is ok if it breaks.

2024-01-19 09:18 UTC, Bella2347 commented on qPCR/qPCR_parser_initial.py
> +    file_content = download_file(lims, args["fileNAME"])
It is handled in the download_file function.

2024-01-19 09:20 UTC, Bella2347 commented
I have test run the changes in the last commits against my test steps and they work.

2024-01-19 09:23 UTC, ErikBergman commented on customPackageSMD/ServerMap.py
> +    def contains(self, item_id):
I think I put this comment in the wrong place. Oh well.

2024-01-22 07:32 UTC, merged