Kapa-Twist sequencing QC email update
Clinical-Genomics-Lund/clarity_scripts pull request #64
Opened 2024-02-18 14:12 UTC by maryemsalim

Restructured the whole script. 
Updated the script to send emails for failed samples as well.
Added python logging.  
Changed tabs to 4 spaces. 
Renamed variables (tried to follow PEP8). 
Script is tested on 10 samples, one for each category (myeloid, onco pred, onco creen, ovarian, test) + failed/passed.
Email only sent to myself when testing, did not use processUDF lists to avoid sending confusing emails.

2024-02-20 12:35 UTC, Bella2347 requested changes
As a whole I think it looks really good! 
I made a lot of comments but they are mostly just syntax and smaller things. 
I have recently learned a few new ways of doing things and have left suggestions for that :)

2024-02-26 07:28 UTC, Bella2347 approved these changes

2024-02-26 20:03 UTC, merged

2024-02-27 08:22 UTC, ErikBergman reviewed
Looks good, I added two comments on code readability

2024-03-04 10:35 UTC, maryemsalim commented on kapaTwist/TWIST_sendEmail_OnkoOvarisMyel.py
> +        first_line = first_line + "\n\n!!There are urgent samples!!\n%s\n\n" % "\n".join(urgent)
Thanks. Definately agree with you on this one. The PR is already merged, but I'll have this suggestion in mind for future changes in the script.